# Generated by Django 5.2.6 on 2025-11-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('prevision', models.CharField(max_length=50)),
                ('accidente_laboral', models.BooleanField(default=False)),
                ('comorbilidades', models.TextField(blank=True)),
                ('funcionalidad', models.CharField(max_length=100)),
                ('motivo_derivacion', models.TextField()),
                ('prestacion_requerida', models.TextField()),
                ('glasgow', models.IntegerField()),
                ('llenado_capilar', models.CharField(max_length=20)),
                ('fc', models.IntegerField()),
                ('fr', models.IntegerField()),
                ('fio2', models.CharField(max_length=10)),
                ('sat02', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuario')),
            ],
        ),
    ]
