# Generated by Django 5.2.6 on 2025-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_paciente_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='Enviado', max_length=30),
        ),
    ]
