# Generated by Django 5.2.6 on 2025-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('En tránsito', 'En tránsito'), ('Recibido', 'Recibido')], default='Enviado', max_length=20),
        ),
    ]
