# Generated by Django 5.2.6 on 2025-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='leido',
        ),
        migrations.AddField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Solucionado', 'Solucionado')], default='Pendiente', max_length=20),
        ),
    ]
